2024-12-04 19:05:28 UTC
Windows-10-10.0.19045
Ren'Py 8.3.3.24111502

Early init took 0.14s
Loading error handling took 0.08s
Loading script took 1.59s
Loading save slot metadata took 0.05s
Loading persistent took 0.00s

Full traceback:
  File "game/artificial_character.rpy", line 2, in script
    init python:
  File "D:\renpy\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/artificial_character.rpy", line 5, in <module>
    from characterai import pycai
  File "D:\renpy\renpy\loader.py", line 892, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/characterai/__init__.py", line 8, in <module>
  File "D:\renpy\renpy\loader.py", line 892, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/characterai/aiocai/__init__.py", line 8, in <module>
  File "D:\renpy\renpy\loader.py", line 892, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/characterai/aiocai/client.py", line 4, in <module>
  File "D:\renpy\renpy\loader.py", line 892, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/characterai/aiocai/methods/__init__.py", line 1, in <module>
  File "D:\renpy\renpy\loader.py", line 892, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/characterai/aiocai/methods/users.py", line 2, in <module>
  File "D:\renpy\renpy\loader.py", line 892, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/characterai/types/user.py", line 3, in <module>
  File "D:\renpy\renpy\loader.py", line 892, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/characterai/types/other.py", line 4, in <module>
  File "D:\renpy\renpy\loader.py", line 892, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/curl_cffi/__init__.py", line 47, in <module>
ModuleNotFoundError: No module named '_cffi_backend'

While running game code:
  File "game/artificial_character.rpy", line 2, in script
    init python:
  File "game/artificial_character.rpy", line 5, in <module>
    from characterai import pycai
ModuleNotFoundError: No module named '_cffi_backend'
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Interface start took 1.24s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'GeForce 210/PCIe/SSE2'
Version: b'3.3.0'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1735, 976) drawable=(1735, 976)
Maximum texture size: 4096x4096
Resetting cache.
Early init took 9.21s
Loading error handling took 0.05s
Loading script took 1.33s
Loading save slot metadata took 0.04s
Loading persistent took 0.00s

Full traceback:
  File "game/artificial_character.rpy", line 2, in script
    init python:
  File "D:\renpy\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/artificial_character.rpy", line 5, in <module>
    from characterai import pycai
  File "D:\renpy\renpy\loader.py", line 892, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/characterai/pycai/__init__.py", line 8, in <module>
  File "D:\renpy\renpy\loader.py", line 892, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/characterai/pycai/client.py", line 1, in <module>
  File "D:\renpy\renpy\loader.py", line 892, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/characterai/pycai/methods/__init__.py", line 1, in <module>
  File "D:\renpy\renpy\loader.py", line 892, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/characterai/pycai/methods/users.py", line 4, in <module>
  File "D:\renpy\renpy\loader.py", line 892, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/characterai/pycai/methods/utils.py", line 7, in <module>
ImportError: cannot import name 'CurlMime' from 'curl_cffi' (D:\renpy\pytarded\game/python-packages/curl_cffi/__init__.py)

While running game code:
  File "game/artificial_character.rpy", line 2, in script
    init python:
  File "game/artificial_character.rpy", line 5, in <module>
    from characterai import pycai
ImportError: cannot import name 'CurlMime' from 'curl_cffi' (D:\renpy\pytarded\game/python-packages/curl_cffi/__init__.py)
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Interface start took 1.13s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'GeForce 210/PCIe/SSE2'
Version: b'3.3.0'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1735, 976) drawable=(1735, 976)
Maximum texture size: 4096x4096
Resetting cache.
Early init took 16.26s
Loading error handling took 0.05s
Loading script took 1.34s
Loading save slot metadata took 0.04s
Loading persistent took 0.00s

Full traceback:
  File "game/characters.rpy", line 130, in script
    define daveai = ArtificialCharacter(char_token="gkYP1YwR5Gk6YbVMD4v6NjDvn-4Yk-DHlZjooyD9Vdk", token=token)
  File "D:\renpy\renpy\ast.py", line 2235, in execute
    self.set()
  File "D:\renpy\renpy\ast.py", line 2249, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "D:\renpy\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/characters.rpy", line 130, in <module>
    define daveai = ArtificialCharacter(char_token="gkYP1YwR5Gk6YbVMD4v6NjDvn-4Yk-DHlZjooyD9Vdk", token=token)
  File "game/artificial_character.rpy", line 11, in __init__
    self.client = pycai.Client(token=token)
AttributeError: module 'characterai.pycai' has no attribute 'Client'

While running game code:
  File "game/characters.rpy", line 130, in script
    define daveai = ArtificialCharacter(char_token="gkYP1YwR5Gk6YbVMD4v6NjDvn-4Yk-DHlZjooyD9Vdk", token=token)
  File "game/characters.rpy", line 130, in <module>
    define daveai = ArtificialCharacter(char_token="gkYP1YwR5Gk6YbVMD4v6NjDvn-4Yk-DHlZjooyD9Vdk", token=token)
  File "game/artificial_character.rpy", line 11, in __init__
    self.client = pycai.Client(token=token)
AttributeError: module 'characterai.pycai' has no attribute 'Client'
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Interface start took 1.09s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'GeForce 210/PCIe/SSE2'
Version: b'3.3.0'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1735, 976) drawable=(1735, 976)
Maximum texture size: 4096x4096
